### ISSUE TITLE
The Shader overrides FancyMenu textues

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Buuz135/DarkModeEverywhere#10]
Hi, Is it possible to blacklist DME from overriding FancyMenu menus? and DrippyLoading Screen loading screens as it causes weird not-intentional changes to the menu making the menu in some cases unreadable

**Comment by Buuz135** [comment]
Can you post some screenshots of what happens?

**Comment by Saereth** [comment]
I posted some of these in the ftbstaff discord I noticed this as well
This is how the image should look and does look with light mode active on the fancy main menu
https://cdn.discordapp.com/attachments/369881656930205701/1006662443101065346/unknown.png

This is how it looks with darkmode on
https://cdn.discordapp.com/attachments/369881656930205701/1006662442379661332/unknown.png
