### ISSUE TITLE
Ability to disable certain UI's 

### ISSUE THREAD

**Issue by Zoofule** [Buuz135/DarkModeEverywhere#13]
It is frustrating that the dark mode affects the hearts/armor/hunger/exp meter, along with Xaero's Minimap. 

It would be cool if Dark Mode Everywhere could automatically generate a .json of every UI that it affects, along with the ability to disable the effect right in that .json.

**Comment by NielsPilgaard** [comment]
It would be very useful to be able to disable GUIs that don't work well with dark mode, especially books. Have you looked into this @Buuz135? :) 

... sorry for the ping :D

**Comment by Brittank88** [comment]
Wonder if I can write a PR that allows specifying screen names and darkness tint or at the very least a basic blacklist config entry.
