### ISSUE TITLE
[Suggestion] Add translations

### ISSUE THREAD

**Issue by LolJohn11** [Buuz135/DarkModeEverywhere#16]
Please make it a possibility to add translations to the mod.

**Comment by Lordfirespeed** [comment]
version `1.19.2-1.1.1` includes the commit referenced above, so it's now possible to add translations by adding locale JSON files at `src/main/resources/assets/darkmodeeverywhere/lang/`
At the moment, only `en_us.json` is present, so I'm sure contributions would be welcome.
