### ISSUE TITLE
[1.19.2] Origins GUI

### ISSUE THREAD

**Issue by Ibirtem** [Buuz135/DarkModeEverywhere#19]
So, DME affects huds in Origin's mod. 
How need: ![image](https://user-images.githubusercontent.com/54157950/229288797-23d5cb5b-b997-4fd2-8c46-9411949b0abf.png)
How it's look: ![image](https://user-images.githubusercontent.com/54157950/229288808-3ae6e99f-7b03-4b1d-8502-5e7a77a5c173.png)
I guess this problem should have been addressed more to Origin's mod, but im not sure.

**Comment by Buuz135** [comment]
https://github.com/Buuz135/DarkModeEverywhere/commit/9082b06b699de342662c1f4baa63ef4721f99ca1
