### ISSUE TITLE
Dark mode draws white outline over XP level number

### ISSUE THREAD

**Issue by Khaeops** [Buuz135/DarkModeEverywhere#2]
Dark mode causes the XP level number to have a white outline instead of the default black one, which in turn becomes harder or uncomfortable to read.

**Comment by Shorepion** [comment]
![xp-number-visualbug](https://user-images.githubusercontent.com/24994890/172266383-44dab1b9-2509-4a00-a825-e8de7edb2e20.JPG)

**Comment by BakeJake** [comment]
Aswell I use lootbeams and it becomes hard to read at times!
Would be nice to have a setting to enable or disable the "dark assisted font"
 ![image](https://user-images.githubusercontent.com/52101762/177029441-38c47550-1b81-4191-b119-2485f0b32f06.png)
