### ISSUE TITLE
Dark mode button doesn't remember setting on restart

### ISSUE THREAD

**Issue by dhasial** [Buuz135/DarkModeEverywhere#28]
The dark mode setting is reset upon restarting the game. Just clicking "save and exit world" and re-entering doesn't do this, it only happens when the game is completely restarted. Like my other opened issue, this is on 1.19 and the ATM8 modpack.

**Comment by rckymtnrfc** [comment]
This seems to be an issue with 1.1.1.  Reverting to 1.1.0 fixes the problem.

**Comment by rckymtnrfc** [comment]
This problem seems to have returned in 1.19.2-1.1.3.  I updated and on load the client, the GUI was back to normal.  I changed it to the dark mode I prefer, restarted the client and it was back to normal again.

FYI, Forge 43.2.14
