### ISSUE TITLE
Dark mode button overlaps JEI bookmarks button

### ISSUE THREAD

**Issue by pupnewfster** [Buuz135/DarkModeEverywhere#3]
Forge: 39.0.64
DarkModeEverywhere: 1.0.1

Edit: Seems to only at times? When I am in creative inventory it does, when I am in one of my GUIs it doesn't.

**Comment by CitiesXL2815** [comment]
![2022-02-01_12 55 52](https://user-images.githubusercontent.com/8730524/153672226-b6fead85-291e-47e7-a4b3-d13bc30ca773.png)
i have same issue as well
