### ISSUE TITLE
Incompatible with AE2

### ISSUE THREAD

**Issue by zappermax** [Buuz135/DarkModeEverywhere#7]
I'm not sure if this is something I can fix on my end but any GUI exclusively to AE2 doesn't switch to dark mode, all it does is change the font colour.

![image](https://user-images.githubusercontent.com/29196045/163805153-2ec3c6fc-46dd-4343-8ea2-8f3e101e4c54.png)

**Comment by SaphireLattice** [comment]
A stop-gap measure would be giving a denylist for UIs that don't work the best with the dark mode on, as requested in #13...

**Comment by Ninjawolf0007** [comment]
I mentioned the issue [here](https://github.com/AllTheMods/ATM-8/issues/510) in the ATM8 issues, but I also noticed that it works in the ME Pattern Access Terminal but not the other ae2 UIs

**Comment by Lordfirespeed** [comment]
AppliedEnergistics/Applied-Energistics-2#6726

**Comment by Lordfirespeed** [comment]
I can proudly say that there are now releases for 1.18, 1.19.2, 1.19.4, and 1.20.1 that are all compatible with AE2. 
If you have any further problems, please drop a comment here <3
