### ISSUE TITLE
The white pixels on minimap gui/hud would turn to black depend on the dark modes that were selected

### ISSUE THREAD

**Issue by tankyap** [Buuz135/DarkModeEverywhere#8]
I found a issue that the white pixels on [Xaeros Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimapl) GUI/HUD will change to black. (Im also sure that it also do to other mod that has GUI too)

Heres a sreeenshot while dark mode is off:
![Inked2022-05-15_16 46 34_LI](https://user-images.githubusercontent.com/87649059/168464904-12c4df7f-ee42-470a-8e23-32f9b2542b15.jpg)

And heres a screenshot while one of the dark mode is on:
![Inked2022-05-15_16 08 32_LI](https://user-images.githubusercontent.com/87649059/168464969-757dd768-ee12-4183-ad8b-380bfc2ab5b4.jpg)

The black colour would be deep depend on the dark mode you selected on the GUI.(example:the white pixel is full black while chosing perfect👌 Dark mode , the white pixel is grey while chosing toasted dark mode,etc)

(I hope that there's a config to turn on and off for each mod that has GUIs ,to solve this problem)

**Comment by Romoslayer** [comment]
Had this issue with JourneyMap as well.
