### ISSUE TITLE
Removes shader sun and moon when dark mode is on.

### ISSUE THREAD

**Issue by Romoslayer** [Buuz135/DarkModeEverywhere#9]
Removes shader sun and moon when dark mode is on.

Mod version: DarkModeEverywhere-1.18.1-1.0.1
Forge: 1.18.2-40.1.0

Used Rubidium and Oculus along with Complimentary Shaders.

**Comment by dadoirie** [comment]
![image](https://user-images.githubusercontent.com/61109153/180664018-feea82c1-a719-4d8b-89e0-64c853637db3.png)

Mod version: DarkModeEverywhere-1.18.1-1.0.2
Forge: 1.18.2-40.1.68
